# For public, HTTPS servers.
version: '3'

services:
  kobocat:
    environment:
      - KPI_UWSGI_WORKERS_COUNT=${WORKERS_MAX}
      - KPI_UWSGI_CHEAPER_WORKERS_COUNT=${WORKERS_START}
    extra_hosts:
      ${USE_PUBLIC_DNS}- ${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PUBLIC_DNS}- ${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PUBLIC_DNS}- ${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PRIVATE_DNS}- postgres.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- mongo.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- redis-main.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- rabbit.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- redis-cache.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}

  kpi:
    environment:
      - KPI_UWSGI_WORKERS_COUNT=${WORKERS_MAX}
      - KPI_UWSGI_CHEAPER_WORKERS_COUNT=${WORKERS_START}
    extra_hosts:
      ${USE_PUBLIC_DNS}- ${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PUBLIC_DNS}- ${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PUBLIC_DNS}- ${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PRIVATE_DNS}- postgres.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- mongo.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- redis-main.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- rabbit.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- redis-cache.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}

  nginx:
    extra_hosts:
      ${USE_PUBLIC_DNS}- ${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PUBLIC_DNS}- ${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PUBLIC_DNS}- ${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PRIVATE_DNS}- postgres.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- mongo.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- redis-main.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- rabbit.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- redis-cache.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}

  enketo_express:
    extra_hosts:
      ${USE_PUBLIC_DNS}- ${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PUBLIC_DNS}- ${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PUBLIC_DNS}- ${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
      ${USE_PRIVATE_DNS}- postgres.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- mongo.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- redis-main.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- rabbit.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}
      ${USE_PRIVATE_DNS}- redis-cache.${PRIVATE_DOMAIN_NAME}:${MASTER_BACKEND_IP}