KOBOCAT_DJANGO_DEBUG=${DEBUG}
TEMPLATE_DEBUG=${DEBUG}

DJANGO_SETTINGS_MODULE=onadata.settings.kc_environ
ENKETO_VERSION=Express

KOBOCAT_BROKER_URL=amqp://kobocat:kobocat@rabbit.${PRIVATE_DOMAIN_NAME}:5672/kobocat

# Mongo values come from mongo.txt
KOBOCAT_MONGO_HOST=mongo.${PRIVATE_DOMAIN_NAME}
#KOBOCAT_MONGO_PORT=$KOBO_MONGO_PORT
#KOBOCAT_MONGO_NAME=$KOBO_MONGO_DB_NAME
#KOBOCAT_MONGO_USER=$KOBO_MONGO_USER
#KOBOCAT_MONGO_PASS=$KOBO_MONGO_PASS

