DJANGO_DEBUG=${DEBUG}
TEMPLATE_DEBUG=${DEBUG}
${USE_X_FORWARDED_HOST}USE_X_FORWARDED_HOST=True

DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
DJANGO_SESSION_COOKIE_AGE=${DJANGO_SESSION_COOKIE_AGE}
DJANGO_ALLOWED_HOSTS=.${PUBLIC_DOMAIN_NAME} .${INTERNAL_DOMAIN_NAME}
KPI_PREFIX=/

SESSION_COOKIE_DOMAIN=".${PUBLIC_DOMAIN_NAME}"

CELERY_BROKER_URL=redis://{% if REDIS_PASSWORD %}:${REDIS_PASSWORD}@{% endif REDIS_PASSWORD %}redis-main.${PRIVATE_DOMAIN_NAME}:${REDIS_MAIN_PORT}/1
CELERY_AUTOSCALE_MIN=2
CELERY_AUTOSCALE_MAX=6

# Comma separated domains
${USE_SERVICE_ACCOUNT_WHITELISTED_HOSTS}SERVICE_ACCOUNT_WHITELISTED_HOSTS=${KOBOFORM_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME},${KOBOCAT_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME}

# See "api key" here: https://github.com/kobotoolbox/enketo-express/tree/master/config#linked-form-and-data-server.
ENKETO_API_KEY=${ENKETO_API_KEY}

# The initial superuser's username.
KOBO_SUPERUSER_USERNAME=${KOBO_SUPERUSER_USERNAME}
# The initial superuser's password.
KOBO_SUPERUSER_PASSWORD=${KOBO_SUPERUSER_PASSWORD}
# The e-mail address where your users can contact you.
KOBO_SUPPORT_EMAIL=${DEFAULT_FROM_EMAIL}

KOBOFORM_URL=${PUBLIC_REQUEST_SCHEME}://${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}${NGINX_PUBLIC_PORT}
KOBOFORM_INTERNAL_URL=http://${KOBOFORM_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME} # Always use HTTP internally.
ENKETO_URL=${PUBLIC_REQUEST_SCHEME}://${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}${NGINX_PUBLIC_PORT}
ENKETO_INTERNAL_URL=http://${ENKETO_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME} # Always use HTTP internally.
KOBOCAT_URL=${PUBLIC_REQUEST_SCHEME}://${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}${NGINX_PUBLIC_PORT}
KOBOCAT_INTERNAL_URL=http://${KOBOCAT_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME} # Always use HTTP internally.
