ENKETO_REDIS_MAIN_HOST=redis-main.${PRIVATE_DOMAIN_NAME}
ENKETO_REDIS_CACHE_HOST=redis-cache.${PRIVATE_DOMAIN_NAME}
ENKETO_LINKED_FORM_AND_DATA_SERVER_SERVER_URL=${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}
ENKETO_LINKED_FORM_AND_DATA_SERVER_API_KEY=${ENKETO_API_KEY}
ENKETO_SUPPORT_EMAIL=${DEFAULT_FROM_EMAIL}
