# For public, HTTPS servers.

services:
  kpi:
  ${USE_KPI_DEV_MODE}  build: ${KPI_PATH}
  ${USE_KPI_DEV_MODE}  image: kpi:dev.${KPI_DEV_BUILD_ID}
  ${USE_KPI_DEV_MODE}  volumes:
  ${USE_KPI_DEV_MODE}    - ${KPI_PATH}:/srv/src/kpi
    environment:
      - UWSGI_WORKERS_COUNT=${UWSGI_WORKERS_MAX}
      - UWSGI_CHEAPER_WORKERS_COUNT=${UWSGI_WORKERS_START}
      - UWSGI_MAX_REQUESTS=${UWSGI_MAX_REQUESTS}
      - UWSGI_CHEAPER_RSS_LIMIT_SOFT=${UWSGI_SOFT_LIMIT}
      - UWSGI_HARAKIRI=${UWSGI_HARAKIRI}
      - UWSGI_WORKER_RELOAD_MERCY=${UWSGI_WORKER_RELOAD_MERCY}
      - WSGI=${WSGI}
    ${USE_CELERY}  - SKIP_CELERY=True
    ${USE_DEV_MODE}  - DJANGO_SETTINGS_MODULE=kobo.settings.dev
    ${USE_HTTPS}  - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    ${USE_NPM_FROM_HOST}  - FRONTEND_DEV_MODE=host
    ${USE_EXTRA_HOSTS}extra_hosts:
    ${USE_FAKE_DNS}  - ${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - postgres.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - mongo.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-main.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-cache.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${USE_BACKEND_NETWORK}networks:
    ${USE_BACKEND_NETWORK}  kobo-be-network:
    ${USE_BACKEND_NETWORK}    aliases:
    ${USE_BACKEND_NETWORK}      - kpi
    ${USE_BACKEND_NETWORK}      - kpi.docker.container

  worker:
  ${USE_KPI_DEV_MODE}  build: ${KPI_PATH}
  ${USE_KPI_DEV_MODE}  image: kpi:dev.${KPI_DEV_BUILD_ID}
  ${USE_KPI_DEV_MODE}  volumes:
  ${USE_KPI_DEV_MODE}    - ${KPI_PATH}:/srv/src/kpi
    environment:
      - WSGI=${WSGI}
    ${USE_DEV_MODE}  - DJANGO_SETTINGS_MODULE=kobo.settings.dev
    ${USE_HTTPS}  - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    ${USE_EXTRA_HOSTS}extra_hosts:
    ${USE_FAKE_DNS}  - ${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - postgres.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - mongo.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-main.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-cache.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${USE_BACKEND_NETWORK}networks:
    ${USE_BACKEND_NETWORK}  kobo-be-network:
    ${USE_BACKEND_NETWORK}    aliases:
    ${USE_BACKEND_NETWORK}      - worker
    ${USE_BACKEND_NETWORK}      - worker.docker.container

  worker_kobocat:
  ${USE_KPI_DEV_MODE}  build: ${KPI_PATH}
  ${USE_KPI_DEV_MODE}  image: kpi:dev.${KPI_DEV_BUILD_ID}
  ${USE_KPI_DEV_MODE}  volumes:
  ${USE_KPI_DEV_MODE}    - ${KPI_PATH}:/srv/src/kpi
    environment:
      - WSGI=${WSGI}
    ${USE_DEV_MODE}  - DJANGO_SETTINGS_MODULE=kobo.settings.dev
    ${USE_HTTPS}  - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    ${USE_EXTRA_HOSTS}extra_hosts:
    ${USE_FAKE_DNS}  - ${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - postgres.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - mongo.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-main.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-cache.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${USE_BACKEND_NETWORK}networks:
    ${USE_BACKEND_NETWORK}  kobo-be-network:
    ${USE_BACKEND_NETWORK}    aliases:
    ${USE_BACKEND_NETWORK}      - worker_kobocat
    ${USE_BACKEND_NETWORK}      - worker_kobocat.docker.container

  worker_low_priority:
  ${USE_KPI_DEV_MODE}  build: ${KPI_PATH}
  ${USE_KPI_DEV_MODE}  image: kpi:dev.${KPI_DEV_BUILD_ID}
  ${USE_KPI_DEV_MODE}  volumes:
  ${USE_KPI_DEV_MODE}    - ${KPI_PATH}:/srv/src/kpi
    environment:
      - WSGI=${WSGI}
    ${USE_DEV_MODE}  - DJANGO_SETTINGS_MODULE=kobo.settings.dev
    ${USE_HTTPS}  - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    ${USE_EXTRA_HOSTS}extra_hosts:
    ${USE_FAKE_DNS}  - ${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - postgres.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - mongo.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-main.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-cache.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${USE_BACKEND_NETWORK}networks:
    ${USE_BACKEND_NETWORK}  kobo-be-network:
    ${USE_BACKEND_NETWORK}    aliases:
    ${USE_BACKEND_NETWORK}      - worker_low_priority
    ${USE_BACKEND_NETWORK}      - worker.docker.container

  beat:
  ${USE_KPI_DEV_MODE}  build: ${KPI_PATH}
  ${USE_KPI_DEV_MODE}  image: kpi:dev.${KPI_DEV_BUILD_ID}
  ${USE_KPI_DEV_MODE}  volumes:
  ${USE_KPI_DEV_MODE}    - ${KPI_PATH}:/srv/src/kpi
    environment:
      - WSGI=${WSGI}
    ${USE_DEV_MODE}  - DJANGO_SETTINGS_MODULE=kobo.settings.dev
    ${USE_HTTPS}  - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    ${USE_EXTRA_HOSTS}extra_hosts:
    ${USE_FAKE_DNS}  - ${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - postgres.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - mongo.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-main.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-cache.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${USE_BACKEND_NETWORK}networks:
    ${USE_BACKEND_NETWORK}  kobo-be-network:
    ${USE_BACKEND_NETWORK}    aliases:
    ${USE_BACKEND_NETWORK}      - beat
    ${USE_BACKEND_NETWORK}      - beat.docker.container

  nginx:
    environment:
      - NGINX_PUBLIC_PORT=${NGINX_PUBLIC_PORT}
      - UWSGI_PASS_TIMEOUT=${UWSGI_PASS_TIMEOUT}
      - WSGI=${WSGI}
    ${USE_LETSENSCRYPT}ports:
    ${USE_LETSENSCRYPT}  - ${NGINX_EXPOSED_PORT}:80
    ${USE_EXTRA_HOSTS}extra_hosts:
    ${USE_FAKE_DNS}  - ${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - postgres.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - mongo.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-main.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-cache.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    networks:
      kobo-fe-network:
        aliases:
          - ${KOBOFORM_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME}
          - ${KOBOCAT_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME}
          - ${ENKETO_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME}

  enketo_express:
    # `DUMMY_ENV` is only there to avoid extra complex condition to override
    # `enketo_express` section or not. It allows to always this section whatever
    # `USE_EXTRA_HOSTS` and `USE_BACKEND_NETWORK` values are.
    environment:
      - DUMMY_ENV=True
    ${USE_EXTRA_HOSTS}extra_hosts:
    ${USE_FAKE_DNS}  - ${KOBOFORM_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${KOBOCAT_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${USE_FAKE_DNS}  - ${ENKETO_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}:${LOCAL_INTERFACE_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - postgres.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - mongo.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-main.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${ADD_BACKEND_EXTRA_HOSTS}  - redis-cache.${PRIVATE_DOMAIN_NAME}:${PRIMARY_BACKEND_IP}
    ${USE_BACKEND_NETWORK}networks:
    ${USE_BACKEND_NETWORK}  kobo-be-network:
    ${USE_BACKEND_NETWORK}    aliases:
    ${USE_BACKEND_NETWORK}      - enketo_express

${USE_BACKEND_NETWORK}networks:
${USE_BACKEND_NETWORK}  kobo-be-network:
${USE_BACKEND_NETWORK}    name: ${DOCKER_NETWORK_BACKEND_PREFIX}_kobo-be-network
${USE_BACKEND_NETWORK}    external: true
